### ISSUE TITLE
Let players know their backpack ammo count

### ISSUE THREAD

**Issue by PentalginPlus** [Hedgefog/cs-zombie-panic#51]
Players often struggle to understand if they have a certain type of ammo or not, and how to drop it (for example, trying to drop a type of ammo a player don't have can confuse him because there's no dropped ammo and there's no message that his attempt has failed because he has no ammo of that type)
My suggestions:
First, "consrvative" and "hardcore" one: show backpack ammo count in a printed message about switching the ammo type.
Second one, that can be considered "casual": Let players drop ammo using a menu, where items has ammo type and ammo count, for example:
1. Magnum [0/24]
2. Shotgun [12/36]
3. Rifle [0/240]
4. Pistol [14/21]
One less bind, and pressing items with 0 ammo can be blocked via callback, so less confusing.
Thanks!

**Comment by Hedgefog** [comment]
Good enhancement, I partially implemented it in this commit:
https://github.com/Hedgefog/cs-zombie-panic/commit/44a7529de1f389e1bed8753f60ff04ee92f839f1

Players can no longer select ammo, that is not in the inventory, but for sure this is not the implementation. I'll add a HUD to display inventory ammo in the future. The main task is to find the best way to display it. I'm not sure I want to use HUD text, because 4 channels are not really enough and it would be better to have this channel for the notifications.
Thanks for your report.
